repos:

  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        args: [
          "--check",
          "--line-length=120",
        ]
        language: python
        language_version: python3
        require_serial: true
        types: [python]

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        args: [
          "--check",
          "--profile=black",
        ]
        language: python
        require_serial: true
        types: [python]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        args: [
          "--max-line-length=120",
          "--max-doc-length=120"
        ]
        language: python
        require_serial: true
        types: [python]